### ISSUE TITLE
Error starting up with Powerwall only

### ISSUE THREAD

**Issue by phawxby** [Teslemetry/hass-teslemetry#105]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Since updating to 1.9.14 Teslemetry is no longer able to start just show the error below. 

![Screenshot_20240630-225728](https://github.com/Teslemetry/hass-teslemetry/assets/1090602/c2c5fa18-e216-4c16-b43a-305c5fd9e0d4)

### Reproduction steps

1. Have Powerwall only?
2. Use teslemetry?

### Debug logs

```text
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 22:44:05 (2 occurrences)
Last logged: 22:48:10

Error setting up entry Teslemetry for teslemetry
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslemetry/__init__.py", line 178, in async_setup_entry
    models.add(gateway["part_name"])
    ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'add'
```

**Comment by Bre77** [comment]
Ah... yes. Fix release.

**Comment by phawxby** [comment]
Amazing, confirmed fixed. Thanks.
